on:
  push:
    branches: [main]

jobs: 
  Docs:
    name: Testing Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Github Checkout
        uses: actions/checkout@v3
      
      - name: Installing Python Version 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install Doxygen (Ubuntu)
        # Install Doxygen on Ubuntu
        run: sudo apt-get install -y doxygen
      - name: Generate Documentation
        # Generate the documentation using doxygen
        run: doxygen Doxyfile

      - name: Upload Documentation
        # Upload the documentation as an artifact
        uses: actions/upload-artifact@v2
        with:
          name: Documentation
          path: html/
